spring.application.name=springboot-oauth2-googlelogin
server.port=9191
spring.security.oauth2.client.registration.google.clientId=1042409032460-mf76nuq2lib61fghjp4bdqtp0ce92fe8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.clientSecret=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

